### ISSUE TITLE
Duplicate lines in list - Virgin Islands

### ISSUE THREAD

**Issue by waveform06** [dewi-alliance/hplans#23]
In the list twice 

Under (B) British Virgin Islands as Unknown
Under (V) Virgin Islands UK as AU915

AU915 assumed correct but not sure of best naming convention https://en.wikipedia.org/wiki/British_Virgin_Islands

**Comment by gradoj** [comment]
British Virgin Islands are currently Unknown region and should be listed as AU915 lorawan region. Duplicate entry should from csv needs to be deleted as well

![image](https://user-images.githubusercontent.com/7544765/149706723-b64f2329-b31d-46a9-8340-8e157f3da0d7.png)
