### ISSUE TITLE
Deploy DualPlan to ANZ countries

### ISSUE THREAD

**Issue by mikev** [dewi-alliance/hplans#37]
DualPlan is a feature which enables a Helium Gateway to concurrently support both AS923_1 and AU915 devices on a single set of 8 channels.  For AU915's DualPlan we've switched from SB2 to SB6.

After the successful conclusion of a Beta test, the Helium Foundation has announced:

DualPlan will be deployed to the following ANZ countries:
AU, CX, CC, CK, HM, PG, NU, NZ, NF and TK

**Comment by gradoj** [comment]
Changing from AU915 to AS923-1(supporting dualplan): 
AU Australia
CX Christmas Island
CC Cocos [Keeling] Islands
CK Cook Islands
HM Heard Island and McDonald Islands
PG Papua New Guinea
NU Niue
NZ New Zealand
NF Norfolk Island
TK Tokelau

Remaining as AU915
AI Anguilla, AR Argentina, BB Barbados, BZ Belize, BO Bolivia, BR Brazil, CL Chile, CO Colombia, DM Dominica, DO Dominican Republic, EC Ecuador, SV El Salvador, GD Grenada, GT Guatemala, HN Honduras, JM Jamaica, MS Montserrat, NI Nicaragua, PA Panama, PY Paraguay, PE Peru, KN Saint Kitts and Nevis, LC Saint Lucia, VC Saint Vincent and the Grenadines, SR Suriname, TO Tonga, TT Trinidad and Tobago, TC Turks and Caicos Islands, UY Uruguay, VG Virgin Islands UK

**Comment by gradoj** [comment]
![dualplan](https://user-images.githubusercontent.com/7544765/190872508-c86bd82c-d783-4dd3-b45c-952e4f3b160c.gif)
