### ISSUE TITLE
Update Brazil, Australia and New Zealand to new custom plans

### ISSUE THREAD

**Issue by mikev** [dewi-alliance/hplans#42]
Brazil will use AU915_SB1
Australia will use AS923_1C
New Zealand will use AS923_1C

See PR for futher details - https://github.com/helium/sx1302_hal/pull/36

**Comment by gradoj** [comment]
![image](https://user-images.githubusercontent.com/7544765/212520192-fb588c63-cfac-4650-8bbd-3487e0183d04.png)
![image](https://user-images.githubusercontent.com/7544765/212520218-02dcb381-2fc2-42da-8993-28b3d9113799.png)
