### ISSUE TITLE
AU915 rollback - external territories

### ISSUE THREAD

**Issue by leogaggl** [dewi-alliance/hplans#45]
Prior to changing the whole region to AS923_1 there were quite a number of external territories and countries that implement Australian standards on AU915.

The rollback seems to have considered only Australian mainland.

The prior list

```
Australia                     AU915
NewZealand                    AU915
Tokelau                       AU915
PapuaNewGuinea                AU915
NorfolkIsland                 AU915
Niue                          AU915
HeardIslandandMcDonaldIslands AU915
CookIslands                   AU915
ChristmasIsland               AU915
CocosIslands                  AU915
TimorLeste                    AU915
Tonga                         AU915

```

Generally these are considered with AU regulations:

- ChristmasIsland
- NorfolkIsland
- TimorLeste
- CocosIslands
- HeardIslandandMcDonaldIslands
- PapuaNewGuinea

Whereas these with NZ regulations:

- Tonga
- Tokelau
- Niue
- CookIslands

Can this please be fixed as part of the rollback.

**Comment by gradoj** [comment]
ignore the regions.csv file for now and just look here in the geojson file. i think they are all correct
https://github.com/dewi-alliance/hplans/blob/main/AU915.geojson

**Comment by waveform06** [comment]
Australia                     Changing
NorfolkIsland                 Changing
HeardIslandandMcDonaldIslands Changing
ChristmasIsland               Changing
CocosIslands                  Changing
TimorLeste                    Unknown,  Not Australian Territory
PapuaNewGuinea                AS923, Not Australian Territory

**Comment by leogaggl** [comment]
This was definitely not a claim for Australian territory. 

They were AU915 prior to the switch and generally implement Australian standards due to the close economic and other ties.

It would be the same with Tongo and others listed with NZ obviously.

**Comment by mikev** [comment]
@mcauser - Thanks for taking a look at the stats.

The Foundation's policy is always to examine each country individually, given a country has it's own sovereignty and regulations.  As of today we plan to continue to support and align with the LoRa Alliance's endorsed plan whenever possible.

Regarding the question of rollback, which is understood to only apply to Australia - only the following countries are governed by Australia:
NorfolkIsland
HeardIslandandMcDonaldIslands
ChristmasIsland
CocosIslands

The Australian regulations allow both AU915 and AS923.  The LoRa Alliance's intent has been to harmonize the entire region to AS923.  In any case, these four provinces have no LoRaWAN sensor traffic at all.  So, there is no urgency either way here that we're aware of.
