### ISSUE TITLE
Brazil, Iraq, New Zealand and Sierre Leone

### ISSUE THREAD

**Issue by mikev** [dewi-alliance/hplans#46]
Switch Brazil from AU915 to AU915_SB1
Switch New Zealnd from AS923_1 to AS923_1C
Configure Iraq to EU868
Configure Sierra Leone to EU868

When complete update lorawan-h3
https://github.com/helium/lorawan-h3/issues/36

**Comment by waveform06** [comment]
Iraq finally got a frequency approved
