### ISSUE TITLE
Rollback Brazil from AU915_SB1 back to SB2

### ISSUE THREAD

**Issue by mikev** [dewi-alliance/hplans#48]
We can either switch Brazil to the AU915_SB2 region.  In other words just copy AU915_SB1 to AU915_SB2
Or we can add Brazil back into the AU915 region.

Afterwards the plan is to run a "vote" with Brazil for the change sponsored by BrDot.

**Comment by abhay** [comment]
potentially a "vote" but at least a comment period.

**Comment by mikev** [comment]
Completed.
