### ISSUE TITLE
RP002-1.0.4 Update

### ISSUE THREAD

**Issue by mikev** [dewi-alliance/hplans#50]
LoRaWAN® Regional Parameters RP002-1.0.4 was published Sep 2022
Update Helium's Regions to conform to RP002-1.0.4
https://resources.lora-alliance.org/technical-specifications/rp002-1-0-4-regional-parameters

Changes identified
Mauritius - EU433 -> EU868
~~Guyana - US915 -> Unknown~~
Bonaire, Sint Eustatius and Saba (BQ) - EU868 -> Prohibited
Algeria AS923-3 -> EU868

**Comment by abhay** [comment]
@mikev is this considered resolved/deployed?

**Comment by mikev** [comment]
This is still pending.  Note we'll keep Guyana at US915 based on feedback we received from an operator in Guyana.
